const mockMovies = [
    {
        id: 27205,
        title: "Inception",
        media_type: "movie",
        release_date: "2010-07-15",
        poster_path: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop",
        vote_average: 8.37,
        overview: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    },
    {
        id: 66732,
        name: "Stranger Things",
        media_type: "tv",
        first_air_date: "2016-07-15",
        poster_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop",
        vote_average: 8.62,
        overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    },
    {
        id: 155,
        title: "The Dark Knight",
        media_type: "movie",
        release_date: "2008-07-16",
        poster_path: "https://images.unsplash.com/photo-1509347528160-9a9e33742cd8?q=80&w=600&auto=format&fit=crop",
        vote_average: 8.51,
        overview: "When the menace known as the Joker wreaks havoc and chaos on Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice.",
    },
    {
        id: 119051,
        name: "Wednesday",
        media_type: "tv",
        first_air_date: "2022-11-23",
        poster_path: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop",
        vote_average: 8.45,
        overview: "A sleuthing, supernaturally infused mystery charting Wednesday Addams' years as a student at Nevermore Academy.",
    },
    {
        id: 157336,
        title: "Interstellar",
        media_type: "movie",
        release_date: "2014-11-05",
        poster_path: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&auto=format&fit=crop",
        vote_average: 8.42,
        overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel.",
    },
    {
        id: 94605,
        name: "Arcane",
        media_type: "tv",
        first_air_date: "2021-11-06",
        poster_path: "https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=600&auto=format&fit=crop",
        vote_average: 8.74,
        overview: "Amid the party towns and oppressive underground of Piltover and Zaun, two sisters fight on opposite sides of a war between band technologies and incompatible beliefs.",
    },
    {
        id: 299536,
        title: "Avengers: Infinity War",
        media_type: "movie",
        release_date: "2018-04-25",
        poster_path: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop",
        vote_average: 8.25,
        overview: "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos.",
    },
    {
        id: 1399,
        name: "Game of Thrones",
        media_type: "tv",
        first_air_date: "2011-04-17",
        poster_path: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop",
        vote_average: 8.44,
        overview: "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war.",
    },
    {
        id: 550,
        title: "Fight Club",
        media_type: "movie",
        release_date: "1999-10-15",
        poster_path: "https://images.unsplash.com/photo-1509347528160-9a9e33742cd8?q=80&w=600&auto=format&fit=crop",
        vote_average: 8.43,
        overview: "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.",
    },
    {
        id: 82856,
        name: "The Mandalorian",
        media_type: "tv",
        first_air_date: "2019-11-12",
        poster_path: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&auto=format&fit=crop",
        vote_average: 8.46,
        overview: "After the fall of the Empire, a lone gunfighter makes his way through the outer reaches of the lawless galaxy.",
    },
    {
        id: 680,
        title: "Pulp Fiction",
        media_type: "movie",
        release_date: "1994-09-10",
        poster_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop",
        vote_average: 8.49,
        overview: "A burger-loving hitman, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in four tales of violence and redemption.",
    },
    {
        id: 60625,
        name: "Rick and Morty",
        media_type: "tv",
        first_air_date: "2013-12-02",
        poster_path: "https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=600&auto=format&fit=crop",
        vote_average: 8.70,
        overview: "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures.",
    },
    {
        id: 13,
        title: "Forrest Gump",
        media_type: "movie",
        release_date: "1994-06-23",
        poster_path: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop",
        vote_average: 8.47,
        overview: "A man with a low IQ has accomplished great things in his life and been present during significant historic events—each time, far exceeding what anyone imagined he could do.",
    }
];

export default mockMovies;